apiVersion: apps/v1
kind: Deployment
metadata:
  name: ki
spec:
  replicas: {{ .Values.ki.replicas }}
  selector:
    matchLabels:
      app: ki
  template:
    metadata:
      labels:
        app: ki
    spec:
      containers:
        - name: ki
          image: {{ .Values.global.imageRepository }}:{{ .Values.global.imageTag }}
          command: ["an-ki", "ki"]
          env:
            - name: AMQP_ADDR
              value: {{ .Values.global.amqpAddr | quote }}
            - name: JWT_SECRET_KEY
              value: {{ .Values.global.jwtSecretKey | quote }}
            - name: DATABASE_URL
              value: {{ .Values.global.databaseUrl | quote }}
          ports:
            - containerPort: 3030
