receivers:
  otlp:
    protocols:
      grpc:
      http:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'an-ki'
          static_configs:
            - targets: ['principal:9090','an:9090','ki:9090']

exporters:
  prometheus:
    endpoint: ":9464"
  logging:
    loglevel: debug

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [prometheus, logging]
    traces:
      receivers: [otlp]
      exporters: [logging]
